name: Hello World

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print Hello World
      run: echo "Hello, World!"
